### ISSUE TITLE
Couple issues I'm having

### ISSUE THREAD

**Issue by SoloTwo** [Mogli12/GearboxAddon#91]
I'll just make a list of some small issues I've been noticing.  

Since the first release candidate update a few days ago it seems the Ford 8240 I'm using seems to now have a parking brake when I come to a stop?  Normally I could just release the clutch slowly without applying any gas and I could start moving easily.  Now no matter what the tractor will stay stationary unless I apply some gas, almost as if there is a parking brake applied.  After further testing, it seems to happen at random, usually only with some sort of tool attached.

For awhile now I've had issues with the combine hydrostatic transmission.  While using the Case IH1660 to thresh I will move my hand throttle to full and engage the combine.  I then use the cruise control to simulate the forward/reverse speed joystick to accelerate and decelerate.  The problem is that if I set it to say 4mph the combine will just crawl along at 1mph.  To actually accelerate to the proper speed I have to shuttle from forward to reverse and back again and it will work as normal.  This only happens when I have the hand throttle set to full and the combine is turned on.  

When pulling implements with a CVT-equipped tractor that doesn't require PTO power, when a load is introduced onto the tractor the RPM's will fluctuate up and down rapidly.  I don't really remember this always being the case but I could be wrong.  To rectify it I just have to set the RPM with the hand throttle and it will stay at a stable RPM.

**Comment by Mogli12** [comment]
Hi,

Thanks for the great problem report. I do not know if I already identified and fixed your 2nd problem. I hope that the 1st and 3rd problems are fixed with 2.0.0.7

Regards, Stefan

**Comment by SoloTwo** [comment]
I wasn't able to use the Combine yesterday so I'll do my best to give it a try today.  :)

**Comment by SoloTwo** [comment]
The first problem seems to be 100% fixed, haven't noticed it since.  

I still haven't been able to get a combine out to test my 2nd problem, but I assume its fixed.

For my third problem, at least with the latest update it still appears to exist.  I didn't notice it yesterday but I was only pulling some heavy trailers.  Today while doing plowing and cultivating with a CVT the RPM's were very erratic whenever a higher load was placed on the tractor.  On smooth ground at around 80% load it would stay at the 1330rpm's, but when a slight increase of load occurred the RPM's would jump up and down.  By setting the hand throttle at any rpm it would keep the RPM's constant at 1330 RPM.  Though problems would occur if you needed more power, increasing the hand throttle would be required.   

At this time I use the Massey 7720 with the Fendt CVT instead of the Dyna-6.  But after the latest update, I did try it with the default setup and I had some issues with the transmission in the auto setting.  Perhaps I'm just using it incorrectly.  For instance, I was mowing, and I'd prefer to use the cruise control to simulate the in-cab joystick for controlling and changing my speed.  When using cruise control in auto mode and switching to reverse and then forward the tractor would usually get stuck in a very low gear, sometimes A1, and refuse to automatically shift up to the correct gear.  This seems to only happen with the PTO engaged.  Sometimes the tractor will increase speed very slowly in auto mode from a stop.  

It's possible that I'm just doing things wrong as my knowledge of driving tractors with a powershift style transmission is pretty low.
